[knx]
gateway = "10.5.35.11"

[room."Kleiner Meetingraum"]
power_state.switch_ga = "3/0/0"
power_state.status_ga = "3/0/1"
power_state.protocol = "pjlink"
power_state.host = "1.2.3.4"

zeevee.output = "Fernseher Kleiner Meetingraum"

zeevee.input."HDMI Kabel Kleiner Meetingraum".switch_ga = "3/0/2"
zeevee.input."HDMI Kabel Kleiner Meetingraum".status_ga = "3/0/3"

zeevee.input."AppleTV Kleiner Meetingraum".switch_ga = "3/0/4"
zeevee.input."AppleTV Kleiner Meetingraum".status_ga = "3/0/5"

zeevee.input."ChromeCast Kleiner Meetingraum".switch_ga = "3/0/6"
zeevee.input."ChromeCast Kleiner Meetingraum".status_ga = "3/0/7"


[room."Großer Meetingraum"]
power_state.switch_ga = "3/1/0"
power_state.status_ga = "3/1/1"
power_state.protocol = "pjlink"
power_state.host = "1.2.3.4"

zeevee.output = "Beamer Großer Meetingraum"

zeevee.input."HDMI Kabel Großer Meetingraum".switch_ga = "3/1/2"
zeevee.input."HDMI Kabel Großer Meetingraum".status_ga = "3/1/3"

zeevee.input."AppleTV Großer Meetingraum".switch_ga = "3/1/4"
zeevee.input."AppleTV Großer Meetingraum".status_ga = "3/1/5"

zeevee.input."ChromeCast Großer Meetingraum".switch_ga = "3/1/6"
zeevee.input."ChromeCast Großer Meetingraum".status_ga = "3/1/7"
