[knx]
gateway = "10.5.35.11"

[room."Kleiner Meetingraum"]
power_state.group_address = "3/0/0"
power_state.protocol = "pjlink"
power_state.host = "1.2.3.4"

zeevee.output = "Fernseher Kleiner Meetingraum"

zeevee.input."HDMI Kabel Kleiner Meetingraum".group_address = "3/0/1"
zeevee.input."AppleTV Kleiner Meetingraum".group_address = "3/0/2"
zeevee.input."ChromeCast Kleiner Meetingraum".group_address = "3/0/3"
