[knx]
gateway = "10.5.35.11"

[output.kleiner_meetingraum]
name = "Kleiner Metingraum"

[output.kleiner_meetingraum.power]
group_address = "3/0/30"
protocol = "dummy"
password = "foobar23"
host = "screen.small-room.smedia.tools"

[output.kleiner_meetingraum.mux]
protocol = "dummy"
zeevee_output = "Fernseher Kleiner Meetingraum"

[output.kleiner_meetingraum.mux.input.hdmi]
group_address = "3/0/31"
zeevee_name = "HDMI Kabel Kleiner Meetingraum"

[output.kleiner_meetingraum.mux.input.appletv]
group_address = "3/0/32"
zeevee_name = "AppleTV Kleiner Meetingraum"

[output.kleiner_meetingraum.mux.input.chromecast]
group_address = "3/0/33"
zeevee_name = "ChromeCast Kleiner Meetingraum"
