[knx]
gateway = "10.5.35.11"

[output.kleiner_meetingraum]
name = "Kleiner Metingraum"

[output.kleiner_meetingraum.power]
group_address = "3/0/0"
group_address_sta = "3/0/100"
protocol = "pjlink"
password = "foobar23"
host = "screen.small-room.smedia.tools"

[output.kleiner_meetingraum.mux]
protocol = "zeevee"
zeevee_output = "Fernseher Kleiner Meetingraum"
host = "zeevee-controller.smedia.tools"

[output.kleiner_meetingraum.mux.input.hdmi]
group_address = "3/0/1"
group_address_sta = "3/0/101"
zeevee_name = "HDMI Kabel Kleiner Meetingraum"

[output.kleiner_meetingraum.mux.input.appletv]
group_address = "3/0/2"
group_address = "3/0/102"
zeevee_name = "AppleTV Kleiner Meetingraum"

[output.kleiner_meetingraum.mux.input.chromecast]
group_address = "3/0/3"
group_address_sta = "3/0/103"
zeevee_name = "ChromeCast Kleiner Meetingraum"

[output.eventspace]
name = "Eventspace"
auto_power_on = false

[output.eventspace.power]
group_address = "3/1/0"
group_address_sta = "3/1/0"
protocol = "pjlink"
password = "foobar23"
host = "beamer.eventspace.smedia.tools"

[output.kleiner_meetingraum.mux]
protocol = "zeevee"
zeevee_output = "Beamer Eventspace"
host = "zeevee-controller.smedia.tools"

[output.kleiner_meetingraum.mux.input.hdmi-buehne]
group_address = "3/0/1"
group_address_sta = "3/0/101"
zeevee_name = "HDMI Kabel Buehne Eventspace"

[output.kleiner_meetingraum.mux.input.appletv]
group_address = "3/0/2"
group_address_sta = "3/0/102"
zeevee_name = "AppleTV Eventspace"

[output.kleiner_meetingraum.mux.input.chromecast]
group_address = "3/0/3"
group_address_sta = "3/0/103"
zeevee_name = "ChromeCast Eventspace"

[output.kleiner_meetingraum.mux.input.hdmi-regie]
group_address = "3/0/4"
group_address_sta = "3/0/104"
zeevee_name = "HDMI Kabel Regie Eventspace"
